### ISSUE TITLE
M2 test spec

### ISSUE THREAD

**Issue by wenjing** [verifiablesoftware/vsw#11]
spec out test cases for testing M1
test cases can be described as user stories, using CLI commands or rest api.

**Comment by thilpinen** [comment]
This is waiting for the CI/CD to work to the point where committed code ends up in a running ECS instance.

**Comment by thilpinen** [comment]
There's been discussion with the developers on the types of tests to run and how to run them; the plan is unfolding.

**Comment by thilpinen** [comment]
Suggest moving activity on this to the M2 test spec ticket.

**Comment by wenjing** [comment]
The test spec should be as follows:

(I) New users
1. new user DID-1, who creates its DID and connects with vsw repo.
2. DID-1 publishes a software credential, test that the repo receives the credential in its wallet
3. new user DID-2, who creates its DID and connects with vsw repo.
4. DID-2 asks for proof from vsw repo and verifies the proof.

(II) Existing users
1. Exisiting user DID-1 publishes a software credential, test that the repo receives the credential in its wallet
2. Existing user DID-2 asks for proof from vsw repo and verifies the proof.

**Comment by wenjing** [comment]
All New user cases passed.
All Existing users cases failed with v0.0.4.
