### ISSUE TITLE
vsw list -cs does not show testCertificate credential

### ISSUE THREAD

**Issue by wenjing** [verifiablesoftware/vsw#111]
I issued a testCertificate credential successfully, but "vsw list -cs" does not show it. It does show softwareCertificate credentials.
root@77220f6dc3ad:/# vsw publish -c workspace/publish_attest.json -s testCertificate
2021-06-01 22:38:33 vsw.commands.attest INFO /usr/local/lib/python3.6/dist-packages/vsw/commands/attest.py executing publish, please waiting for response
2021-06-01 22:38:33 vsw.commands.attest INFO /usr/local/lib/python3.6/dist-packages/vsw/commands/attest.py holder connection_id: ccfefe0e-e05a-4938-ac41-5e45268a08da
2021-06-01 22:38:35 vsw.commands.attest INFO /usr/local/lib/python3.6/dist-packages/vsw/commands/attest.py cred_def_id: 3EgDXzVZ2grXvYXp5MEBnV:3:CL:3949:default
2021-06-01 22:38:35 vsw.commands.attest INFO /usr/local/lib/python3.6/dist-packages/vsw/commands/attest.py credential_exchange_id: 7bca5870-099c-4d92-9a92-aadb46a66ffc
2021-06-01 22:38:36 vsw.commands.attest INFO /usr/local/lib/python3.6/dist-packages/vsw/commands/attest.py waiting state change, current state is: proposal_received
2021-06-01 22:38:37 vsw.commands.attest INFO /usr/local/lib/python3.6/dist-packages/vsw/commands/attest.py waiting state change, current state is: offer_sent
2021-06-01 22:38:39 vsw.commands.attest INFO /usr/local/lib/python3.6/dist-packages/vsw/commands/attest.py waiting state change, current state is: request_received
2021-06-01 22:38:39 vsw.commands.attest INFO /usr/local/lib/python3.6/dist-packages/vsw/commands/attest.py waiting state change, current state is: credential_issued
2021-06-01 22:38:40 vsw.commands.attest INFO /usr/local/lib/python3.6/dist-packages/vsw/commands/attest.py waiting state change, current state is: credential_acked
2021-06-01 22:38:40 vsw.commands.attest INFO /usr/local/lib/python3.6/dist-packages/vsw/commands/attest.py Congratulation, execute publish successfully!
root@77220f6dc3ad:/# 
root@77220f6dc3ad:/# 
root@77220f6dc3ad:/# 
root@77220f6dc3ad:/# 
root@77220f6dc3ad:/# 
root@77220f6dc3ad:/# 
root@77220f6dc3ad:/# pwd
/
root@77220f6dc3ad:/# ls
bin  boot  dev  etc  home  lib  lib64  media  mnt  opt  proc  root  run  sbin  srv  sys  tmp  usr  var  workspace
root@77220f6dc3ad:/# 
root@77220f6dc3ad:/# 
root@77220f6dc3ad:/# 
root@77220f6dc3ad:/# vsw list -cs
{
    'results': [
        {
            'referent': '415a698f-ca4a-4d9f-bead-85d8b0a17d91',
            'attrs': {
                'softwareDid': 'Nmks4aByuqBfbhn1fGY5ew',
                'softwareUrl': 
'https://files.pythonhosted.org/packages/af/a2/269b2d19a6b9fd6dc2b504f91c7562fe9878b6edfecdc4a23407b0e9f872/vsw-0.0.11-py3-none-any.whl',
                'dependencyDidList': '',
                'softwareName': 'vsw',
                'softwareHash': 'z2d9pM8uz5CPu3tZ7xmyyNPVVWyMLzNLdXSRuHfhd5EiVB1VVey2hR3UaGQ9PhAx1Wh4yuMPc6zsE1LiJDNVdxSy5N',
                'builderDid': '',
                'softwareVersion': '0.0.11',
                'buildLog': '',
                'builderToolDidList': '',
                'sourceDid': '',
                'mediaType': '',
                'developerDid': '3EgDXzVZ2grXvYXp5MEBnV',
                'sourceUrl': 
'https://files.pythonhosted.org/packages/7e/27/300a61d019fec87cc9104da199262bd01d15298dc8c21c79b0cb5ffddd5a/vsw-0.0.11.tar.gz',
                'sourceHash': 'z2d9pM8uz5CPu3tZ7xmyyNPVVWyMLzNLdXSRuHfhd5EiVB1VVey2hR3UaGQ9PhAx1Wh4yuMPc6zsE1LiJDNVdxSy5N'
            },
            'schema_id': 'UyDtaEFuTySAV9VZDykHkh:2:softwareCertificate:0.3',
            'cred_def_id': '3EgDXzVZ2grXvYXp5MEBnV:3:CL:3733:default',
            'rev_reg_id': 
'3EgDXzVZ2grXvYXp5MEBnV:4:3EgDXzVZ2grXvYXp5MEBnV:3:CL:3733:default:CL_ACCUM:6e572d50-68b2-4c85-bc6a-1bbe0896d0de',
            'cred_rev_id': '4'
        },
        {
            'referent': '862558cd-39b7-4063-a763-0553479f4600',
            'attrs': {
                'softwareName': 'vsw',
                'sourceHash': 'z2d9pM8uz5CPu3tZ7xmyyNPVVWyMLzNLdXSRuHfhd5EiVB1VVey2hR3UaGQ9PhAx1Wh4yuMPc6zsE1LiJDNVdxSy5N',
                'softwareDid': 'Nmks4aByuqBfbhn1fGY5ew',
                'builderDid': '',
                'softwareHash': 'z2d9pM8uz5CPu3tZ7xmyyNPVVWyMLzNLdXSRuHfhd5EiVB1VVey2hR3UaGQ9PhAx1Wh4yuMPc6zsE1LiJDNVdxSy5N',
                'sourceDid': '',
                'mediaType': '',
                'dependencyDidList': '',
                'buildLog': '',
                'softwareVersion': '0.0.11',
                'developerDid': '3EgDXzVZ2grXvYXp5MEBnV',
                'sourceUrl': 
'https://files.pythonhosted.org/packages/7e/27/300a61d019fec87cc9104da199262bd01d15298dc8c21c79b0cb5ffddd5a/vsw-0.0.11.tar.gz',
                'softwareUrl': 
'https://files.pythonhosted.org/packages/af/a2/269b2d19a6b9fd6dc2b504f91c7562fe9878b6edfecdc4a23407b0e9f872/vsw-0.0.11-py3-none-any.whl',
                'builderToolDidList': ''
            },
            'schema_id': 'UyDtaEFuTySAV9VZDykHkh:2:softwareCertificate:0.3',
            'cred_def_id': '3EgDXzVZ2grXvYXp5MEBnV:3:CL:3733:default',
            'rev_reg_id': 
'3EgDXzVZ2grXvYXp5MEBnV:4:3EgDXzVZ2grXvYXp5MEBnV:3:CL:3733:default:CL_ACCUM:6e572d50-68b2-4c85-bc6a-1bbe0896d0de',
            'cred_rev_id': '2'
        },
        {
            'referent': 'dfeef3aa-c781-4f95-9249-0d0e7c7bf862',
            'attrs': {
                'softwareName': 'vsw',
                'builderDid': '',
                'dependencyDidList': '',
                'sourceHash': 'z2d9pM8uz5CPu3tZ7xmyyNPVVWyMLzNLdXSRuHfhd5EiVB1VVey2hR3UaGQ9PhAx1Wh4yuMPc6zsE1LiJDNVdxSy5N',
                'softwareUrl': 
'https://files.pythonhosted.org/packages/ee/d3/bf2b994670dc77d29c657ffdf1fc763207502c5b95a308dac7db50c3a050/vsw-0.0.10.tar.gz',
                'sourceDid': '',
                'developerDid': '3EgDXzVZ2grXvYXp5MEBnV',
                'softwareVersion': '0.0.10',
                'buildLog': '',
                'mediaType': 'application/vnd.oci.image.manifest.v1+json',
                'builderToolDidList': '',
                'softwareHash': 'z2d9pM8uz5CPu3tZ7xmyyNPVVWyMLzNLdXSRuHfhd5EiVB1VVey2hR3UaGQ9PhAx1Wh4yuMPc6zsE1LiJDNVdxSy5N',
                'softwareDid': 'Nmks4aByuqBfbhn1fGY5ew',
                'sourceUrl': 'https://github.com/verifiablesoftware/vsw/archive/refs/tags/v0.0.10.tar.gz'
            },
            'schema_id': 'UyDtaEFuTySAV9VZDykHkh:2:softwareCertificate:0.3',
            'cred_def_id': '3EgDXzVZ2grXvYXp5MEBnV:3:CL:3733:default',
            'rev_reg_id': 
'3EgDXzVZ2grXvYXp5MEBnV:4:3EgDXzVZ2grXvYXp5MEBnV:3:CL:3733:default:CL_ACCUM:6e572d50-68b2-4c85-bc6a-1bbe0896d0de',
            'cred_rev_id': '1'
        },
        {
            'referent': '8256114f-f3f2-4e86-89aa-350c6f3e227b',
            'attrs': {
                'sourceHash': 'z2d9pM8uz5CPu3tZ7xmyyNPVVWyMLzNLdXSRuHfhd5EiVB1VVey2hR3UaGQ9PhAx1Wh4yuMPc6zsE1LiJDNVdxSy5N',
                'developerDid': '3EgDXzVZ2grXvYXp5MEBnV',
                'builderToolDidList': '',
                'dependencyDidList': '',
                'softwareVersion': '0.0.11',
                'sourceDid': '',
                'mediaType': 'application/vnd.oci.image.manifest.v1+json',
                'buildLog': '',
                'softwareHash': 'z2d9pM8uz5CPu3tZ7xmyyNPVVWyMLzNLdXSRuHfhd5EiVB1VVey2hR3UaGQ9PhAx1Wh4yuMPc6zsE1LiJDNVdxSy5N',
                'softwareDid': 'Nmks4aByuqBfbhn1fGY5ew',
                'builderDid': '',
                'sourceUrl': 
'https://files.pythonhosted.org/packages/7e/27/300a61d019fec87cc9104da199262bd01d15298dc8c21c79b0cb5ffddd5a/vsw-0.0.11.tar.gz',
                'softwareName': 'vsw',
                'softwareUrl': 
'https://files.pythonhosted.org/packages/af/a2/269b2d19a6b9fd6dc2b504f91c7562fe9878b6edfecdc4a23407b0e9f872/vsw-0.0.11-py3-none-any.whl'
            },
            'schema_id': 'UyDtaEFuTySAV9VZDykHkh:2:softwareCertificate:0.3',
            'cred_def_id': '3EgDXzVZ2grXvYXp5MEBnV:3:CL:3733:default',
            'rev_reg_id': 
'3EgDXzVZ2grXvYXp5MEBnV:4:3EgDXzVZ2grXvYXp5MEBnV:3:CL:3733:default:CL_ACCUM:6e572d50-68b2-4c85-bc6a-1bbe0896d0de',
            'cred_rev_id': '3'
        }
    ]
}
root@77220f6dc3ad:/# 
root@77220f6dc3ad:/#

**Comment by felixchen1023** [comment]
fixed now, please verify

**Comment by wenjing** [comment]
Verified fix
