### ISSUE TITLE
Initial invitation & remove adminapi access

### ISSUE THREAD

**Issue by wenjing** [verifiablesoftware/vsw#120]
This problem has several aspects:
- Initial invitation from the vsw-repo should be through a public url (multiple use invitation)
- All other access of repo adminapi should be removed
-- publish : use issuer (client) initiated "Offer" protocol
-- failed revocation: use a controller file to remember issued credentials and their states (active, revoked, failed). This info is then displayed by "vsw list -cs".

**Comment by felixchen1023** [comment]
done

**Comment by tervoju** [comment]
is this now fixed? no changes needed in the Repo`?

**Comment by wenjing** [comment]
Changes are required on verify.json file format. See clitests for examples.
Seems to be working.
