### ISSUE TITLE
initial repo web service release

### ISSUE THREAD

**Issue by wenjing** [verifiablesoftware/vsw#15]

**Comment by TonWolting** [comment]
@tervoju , @thilpinen please give updates and status on vsw-repo build and CD to AWS to this ticket and close when code merged and finalized.

**Comment by thilpinen** [comment]
CI/CD workflow works, the repo code deploys successfully. There's an issue left with the agent start-up that needs a fix.

**Comment by thilpinen** [comment]
Okay, done both for stable and devel versions.
