### ISSUE TITLE
implementation CLI

### ISSUE THREAD

**Issue by wenjing** [verifiablesoftware/vsw#16]
for features not yet realized, return a message. #1 

this specification should be consisted of a high level CLI syntax with brief descriptions. The syntax should be consistent with all user stories where CLI examples are given to illustrate various features. The intent is that this spec can assist in the CLI implementation in M2, and later be used as a starting point for CLI User Manual.

**Comment by TonWolting** [comment]
@ericwang14 for this week delivery (8.1) generic CLI implementation for vsw build and vsw install needs to be implemented. Check with @tervoju for open questions or help on this.

**Comment by ericwang14** [comment]
@wenjing  for the vsw build and vsw install, i wasn't sure what are these commands suppose to do, do you have clear definition(requirements) for them?

**Comment by wenjing** [comment]
> @wenjing for the vsw build and vsw install, i wasn't sure what are these commands suppose to do, do you have clear definition(requirements) for them?

First of all, this issue #16 is to implement regular CLI framework, not specific commands. 
Secondly, I'm not aware of either of those commands. I don't see issues opened for them. If you see them, please refer them here, or better, please post your comments on the right issues.

**Comment by wenjing** [comment]
Specifically, these are currently defined in M2:
- vsw register
- vsw publish
- vsw list
- vsw verify
There was some discussion that we may also need 'vsw init'... but we are waiting for the closure of the design questions. The list for M2 can be finalized then.

**Comment by TonWolting** [comment]
Code commit pushed to Master
