### ISSUE TITLE
vsw integration with sovrin networks

### ISSUE THREAD

**Issue by wenjing** [verifiablesoftware/vsw#19]
#5 implementation.
Please refer to https://github.com/verifiablesoftware/vsw/blob/master/docs/vsw-DID-VC-v1.0.md.
This github issue narrows in the work needed to integrate with Sovrin BuilderNet and StagingNet.

(1) after unit test on local Indy pool, testing should be done with BuilderNet. 
(2) after BuilderNet testing is done, it should be "deployed" on StagingNet - as an experimental production deployment.

During M2, we need to switch from exclusive on local pool to integrating with Sovrin networks. For details, please refer to the above document.

**Comment by TonWolting** [comment]
@tervoju please update status, open issues to this ticket before meeting on 5.1.2021. Thanks!

**Comment by tervoju** [comment]
expected way of working
- aca-py provision to get DID and verkey
- fill in info to https://selfserve.sovrin.org/
- accept the transaction author agreement
- > agent is provisioned


details:
------------------

- sovrin ledger usage 
    assuming using either attribute 
		--genesis-file attribute and the genesis-file
		--genesis-url and https://github.com/sovrin-foundation/sovrin/blob/stable/sovrin/pool_transactions_builder_genesis
		
	get repo agent started with genesis file 
		- agent starts but gets obviously get issues 
		
	can the agent be provisioned and started separately?
		aca-py provision --endpoint 192.168.65.3 --genesis-file ./genesis.txt --wallet-type indy --wallet-key wallet --wallet-name wallet --seed my_seed_000000000000000000009216
		based ont the information on https://ldej.nl/post/connecting-acapy-to-development-ledgers/ that's the way to do it
		page also indicates that user gets propted about 
		
		---->
		It will then ask you to accept the transaction author agreement:
			Please select an option:
				1. Accept the transaction author agreement and store the acceptance in the wallet
				2. Acceptance of the transaction author agreement is on file in my organization
				X. Skip the transaction author agreement
		<----
		Before that user should go to the 
			https://selfserve.sovrin.org/
		and give DID and verkey to the form before accepting.
		tried that but actually the provisioning did not give the DID and verkey? should it?

**Comment by tervoju** [comment]
repo sw
seems to work with sovrin. GET /ledger/taa provides data 
{
  "result": {
    "aml_record": ....,
    "taa_record": ....,
    "taa_required": ...,
    "taa_accepted": null
  }
}   
and POST /ledger/taa can be used to change "taa_accepted" status. 
also inivitation can be created for publishing (same way as in M1)

**Comment by tervoju** [comment]
handled with separate aca-py provision and aca-py start.
