### ISSUE TITLE
vsw publish

### ISSUE THREAD

**Issue by wenjing** [verifiablesoftware/vsw#20]
implement 'vsw publish' command for both publishers (developer and tester).

for M2 deployment, the system must be also tested for deployment on sovrin buildernet and stagingnet, in addition to local pool.

**Comment by tervoju** [comment]
items to be done 
- use real ledger
- postgres to be used
- all use case webhooks and controller end points implemented and working
- vsw-repo running in the vsw and deployment 
- clean up the implementation

**Comment by TonWolting** [comment]
@felixchen1023 please check with Juha for implementing vsw publish. Thanks!

**Comment by wenjing** [comment]
The base behavior test worked. However, webhook/controler has not been implemented appropriately yet. But I'm closing this because the webhook/controller issue is being tracked on #88
