### ISSUE TITLE
vsw list

### ISSUE THREAD

**Issue by wenjing** [verifiablesoftware/vsw#23]
vsw list offers various ways of listing software, credentials, members ... in the repo. Refer to user stories for common use case requirements.
"vsw list" can be seen as a "query" - about information that is in the repo.

For the purpose of M2 milestone, we are looking for a suitable "default" behavior. In future milestones, we can work on filtering options in the list command. The tasks:
1- design vsw list command that can be expanded to include filtering in future
2- design and specify a default behavior - when no filtering option is used
3- implement and demo the default behavior

Note: we need to specify which information in the credential or collected in the publishing and other processes are public or can be disclosed to the user who issues "vsw list". It is ok to assume a default behavior for M2 completion.

**Comment by felixchen1023** [comment]
The following functions are supported now.
vsw list -c: list all the connections
vsw list -w: list all wallet dids
vsw list -sc: list all the schema
vsw list -s: see agent status
vsw list -i: list all the issue credential records
vsw list -cs: list all the credentials
vsw list -cd: list all the credential definitions
