### ISSUE TITLE
ci/cd for M2

### ISSUE THREAD

**Issue by wenjing** [verifiablesoftware/vsw#49]
In M2, ci/cd must be able to work with 3 possible scenarios
- the simulated ledger, as in M1
- the buildernet
- the staging net

Note: looking ahead for M3, we expect the switching of services from one to another - esp. the mode to test in buildernet and then deploy for trial in the stagingnet.

**Comment by thilpinen** [comment]
The scripts starting the repository server are parametrized in order to connect the agent to different ledgers, so we have the capability to switch according to different cases such as build time testing.

**Comment by thilpinen** [comment]
Work underway to parametrize the ledger selection from the CI/CD side.
