### ISSUE TITLE
Software cetificate schema in the ledger

### ISSUE THREAD

**Issue by wenjing** [verifiablesoftware/vsw#59]
As a prior, we need the software credential schema be published in the ledger before anyone can issue credential definition or issue credentials. 
- Define a proto "software-certificate" schema.
- Write the schema to the buildernet ledger (anyone who has endorser role is ok to do this step)
- Read it back using schemaID string to test it is working by any user. The schemaID looks like "mz3AM33qVp54eYYJRp9tw:2834:software-certificate:0.1"

If any arbitrary user can read the schema back successfully, this is working.

**Comment by tervoju** [comment]
"mz3AM33qVp54eYYJRp9tw:2:software-certificate:0.1" worked, so I assume that is done? or is that 2384 relevant information? at least the admin portal does not accept that format.

**Comment by wenjing** [comment]
You are right. I found documentation here describing that field as "SchemaMarker", as a TYPE info for parser/searcher. "2" means SchemaMarker, "3" means CredDefMarker, ... and so on. See more: https://github.com/hyperledger/indy-node/blob/master/design/anoncreds.md.

So the correct schemaID is : "mz3AM33qVp54eYYJRp9tw:2:software-certificate:0.1".

**Comment by wenjing** [comment]
Completed
