### ISSUE TITLE
vsw publish flow chart has inaccuracies

### ISSUE THREAD

**Issue by wenjing** [verifiablesoftware/vsw#60]
https://github.com/verifiablesoftware/vsw/blob/master/docs/communication/vsw%20publish_detailed.png
Problems with this flow chart:
- the connection phase of the protocol is already done at the "vsw setup" time. when a user issues "vsw publish", it should already be connected with the repo.
- credential definition is a step that is done at the "vsw setup" time, and for once only (only during the first run of the vsw setup for a given cred-def). During "publish". the credential definition ID should already be known. So we should search for the cred-def, and if not found, print error message to ask user to use "vsw setup" to create the relevant cred-def.
- in the cli format "vsw publish", it should follow by a local file which has all the necessary credential information. It should not directly reference a url+hash. Checking hash locally is not meaningful - that information is to be issued as part of the credential.
- since we already have a "vsw publish" chart - should we update that chart instead of creating a new one?

This flow chart follows the "Offer", "Request", "Issue" procedure. For background, reference https://github.com/hyperledger/aries-rfcs/tree/master/features/0036-issue-credential.

**Comment by tervoju** [comment]
comments:

- the connection phase of the protocol is already done at the "vsw setup" time. when a user issues "vsw publish", it should already be connected with the repo and credential def are in setup
- I wanted to keep the original publish as I thought there will be comments/corrections to this one
- about hash. assumption here is that hash is calculated locally, not checked. file could be local or url
- invitation: is that separate activity or part of setup?
