### ISSUE TITLE
vsw setup cli implement

### ISSUE THREAD

**Issue by felixchen1023** [verifiablesoftware/vsw#61]
$vsw setup

In the first step, the user installs all software needed to run vsw (which includes aca-py implicitly). Ideally, users don’t need to know aca-py, but if too complicated, it’s ok to have the user explicitly install aca-py as well.

In the second step, the behavior is described in the design doc and is similar to what Juha described above. If aca-py isn’t running,  first start it with properly initial config parameters, then connect with it through the admin api, complete the rest of initialization, issue a “list DID” command to test the interface, print out DID list, e.g.

When you start aca-py, please use config file rather than inline parameters, so users can see the settings a lot easier and make changes. Run both as daemons. We will use “vsw exit” to kill both.

Another step that “vsw setup” should do is to use the admin API to trigger the agent to make a pair-wise connection to the vsw-repo agent and report status.

**Comment by felixchen1023** [comment]
Most of them are all done except using the admin API to trigger the repo agent, since we have not been working vsw-repo.

**Comment by TonWolting** [comment]
For this ticket please use schemaID. For further we need to make it more user friendly and use naming for schemaID. Separate ticket to created for that.

**Comment by felixchen1023** [comment]
--schema function has been done now. create/initial connection to repo has been moved to "vsw init" since this needs to wait until vsw agent starting done.
