### ISSUE TITLE
use admin-api-key aca-py

### ISSUE THREAD

**Issue by tervoju** [verifiablesoftware/vsw#66]
--admin-api-key <api-key>
                        Protect all admin endpoints with the provided API key.
                        API clients (e.g. the controller) must pass the key in
                        the HTTP header using 'X-API-Key: <api key>'. Either
                        this parameter or the '--admin-insecure-mode'
                        parameter MUST be specified. [env var:
                        ACAPY_ADMIN_API_KEY]

**Comment by tervoju** [comment]
implemented

**Comment by felixchen1023** [comment]
@tervoju have you deployed to somewhere, so that I can test it with my local client vsw?

**Comment by tervoju** [comment]
created a pull request for Tero to merge this to main branch
