### ISSUE TITLE
vsw publish: input format change

### ISSUE THREAD

**Issue by wenjing** [verifiablesoftware/vsw#85]
This is a requirement documented in the M3 design doc (a change from M2).
Instead of entering parameters one by one in cli, change to use a credential file in json instead.

% vsw publish --cred <file-name>

Since we are doing that, then all other issues related to publish cli format do not need to fix.

**Comment by felixchen1023** [comment]
It's already done in 0.0.5 version.

**Comment by wenjing** [comment]
Fixed
