### ISSUE TITLE
ci/cd chain

### ISSUE THREAD

**Issue by wenjing** [verifiablesoftware/vsw#9]
develop and test ci/cd chain from github to cloud deployment

**Comment by TonWolting** [comment]
@thilpinen please update this M1 ticket immediately with status and close when finalized. Thanks!

**Comment by thilpinen** [comment]
Current effort is at getting the CI workflow to run through the entire AWS side. In the wsw-repo/ci branch there's now an Actions script that gets as far as pushing the built Docker images to ECR; the deployment needs to point to the correct service in order for the Docker image to end up in the ECS instance that runs it, and it currently doesn't do that.

**Comment by thilpinen** [comment]
The experimental chain now runs on Actions from start to finish, but the resulting image isn't running after deployment. The separation of branch and main workflows is in progress.

**Comment by thilpinen** [comment]
The problem with test deployments from GitHub to AWS has been solved; continuing with branch-specific versions of the GitHub side workflow.

**Comment by thilpinen** [comment]
Forked the repo server code to add the M1 workflow to add and test the split workflow scripts for devel/main branches.

**Comment by thilpinen** [comment]
Deployment from vsw-repo master succeeds.
