### ISSUE TITLE
unable to use revocation

### ISSUE THREAD

**Issue by wenjing** [verifiablesoftware/vsw#94]
version 0.0.4
Because "vsw list -cs" does not list any credentials, a user will not be able to discover any of the parameters required in the "vsw revoke" command, and therefore can't revoke any credential.
See also #89 

Currently the vsw revoke names 3 options to specify the credential to be revoked, we need to make sure that this identifier is saved in wallet so that the number is still available after exiting vsw.

root@a178189822b0:/# vsw revoke
Either the Credential Exchange ID, or Credential Registry ID and Credential Revocation ID are required.
Usage:
vsw revoke [options]
-cei, --credential-exchange-id         The Credential Exchange Id
-reg, --credential-registry-id         The Credential Registry ID
-cei, --credential-revocation-id       The Credential Revocation ID
root@a178189822b0:/# vsw list
Usage:
vsw list 
-c: list all the connections
-w: list all wallet dids
-sc: list all the schema
-s: see agent status
-i: list all the issue credential records
-p: list all present proof records
-cs: list all the credentials
-cd: list all the credential definitions
root@a178189822b0:/# 
root@a178189822b0:/# vsw list -cs
[20:39:04] {'results': []}

**Comment by wenjing** [comment]
Yes - the debug info prints out CEI so I can continue, but not to a real user once we remove INFO printing.

**Comment by wenjing** [comment]
Verified that by using Rev_Reg_Id and credential rev id together, revoke command works.
Still open question where to get CEI other than the printout of "vsw publish".

**Comment by felixchen1023** [comment]
already -cei parameter, and change name for -reg and rev

**Comment by felixchen1023** [comment]
already removed -cei parameter, and change name for -reg and rev

**Comment by wenjing** [comment]
verified in 0.0.20
