### ISSUE TITLE
vsw list command issues

### ISSUE THREAD

**Issue by wenjing** [verifiablesoftware/vsw#99]
Here is how the "vsw list" command works today:

root@bc05ac57d34e:/# vsw list
Usage:
vsw list 
-c: list all the connections
-w: list all wallet dids
-sc: list all the schema
-s: see agent status
-i: list all the issue credential records
-p: list all present proof records
-cs: list all the credentials
-cd: list all the credential definitions

Here are the issues and how we could fix them:

(1) -sc
Since we no longer create new schemas in vsw client, we should either remove this, or, print the information of the schemas we support including "schema ID" and its json format.

(2) -i does show anything, is -i and -cs the same thing? Please clean up these two so we list credentials that have been issued by the current DID, or wallet

(3)fix grammar etc...
Usage:
vsw list 
-c: list all connections
-w: list all DIDs in the wallet
-sc: list all supported schemas
-s: show agent status
-i: list all issued credential records /*maybe remove?*/
-p: list all presentation proof records
-cs: list all credentials issued by the current DID
-cd: list all credential definitions registered by the current DID

**Comment by felixchen1023** [comment]
already fixed. please test again

**Comment by wenjing** [comment]
Verified fix
